# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "15 * * * *"  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autocommit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: Roll_dice
        run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV
        shell: bash

      - if: env.PROCEED == '0'
        name: Cancelling
        uses: andymckay/cancel-action@0.2

      - if: env.PROCEED == '0'
        name: Waiting for cancellation
        run: sleep 60

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Auto Commit
        run: |
          git config --local user.email "ziwiiii3@gmail.com"
          git config --local user.name "Weiyu Zeng"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "[UPDATE] Auto Commit"
          git push
